# Numpy Basics

In [6]:
import numpy as np

a1 = np.array([1, 2, 3])
print('array1  type:', type(a1))
print('array1 shape:', a1.shape)

a2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2  type:', type(a2))
print('array2 shape:', a2.shape)

array1  type: <class 'numpy.ndarray'>
array1 shape: (3,)
array2  type: <class 'numpy.ndarray'>
array2 shape: (2, 3)


# NumPy Array
1. simple array
  - simple too
  - jump ahead
1. this

[Google](http://www.google.com)


In [3]:
a3 = np.array([[1, 2, 3]])
print('array3  type:', type(a3))
print('array3 shape:', a3.shape)



array3  type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [10]:
print('array1: {0:2d}차원, array2: {1:02d}차원, array2:{2}차원'.format(a1.ndim, a2.ndim, a3.ndim))

array1:  1차원, array2: 02차원, array2:2차원


In [11]:
list1 = list(range(10))
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] int32


In [16]:
Z = np.zeros((3,2),dtype='uint32')
U = np.ones((3,2))
print(Z, U)

[[0 0]
 [0 0]
 [0 0]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
M = np.arange(10)
print(type(M))
print(M.shape)
print(M)
N = M.reshape(2,5)
print(N)
P = M.reshape(5,-1)
print(P)
print(P.tolist())
print(P[:])

<class 'numpy.ndarray'>
(10,)
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
C = np.arange(2, 12, 2)
print(C)
t = np.linspace(0, np.pi, 100, 'True')
print(t)

[ 2  4  6  8 10]
[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.

In [41]:
M1 = np.random.permutation(16).reshape(4,4)
print(M1)
m3 = M1[:,1:]
print(m3)
print(M1[[0,2]])

[[ 1  2 14  0]
 [13  9 11 15]
 [ 7 10  3  4]
 [ 6  5 12  8]]
[[ 2 14  0]
 [ 9 11 15]
 [10  3  4]
 [ 5 12  8]]
[[ 1  2 14  0]
 [ 7 10  3  4]]


In [45]:
P = np.random.permutation(10)
print(P)
Q = P[P<5]
P[P>5] = 5
print(P, Q)

[6 3 2 0 4 5 8 9 7 1]
[5 3 2 0 4 5 5 5 5 1] [3 2 0 4 1]


In [ ]:
S = np.sort(Q)
print(S)
print(Q)
Q.sort()
print(Q)

In [63]:
R = np.random.random([4,4])
np.set_printoptions(precision=3)
print(R)
print(np.sort(R,axis=0))
A = np.argsort(R,axis=0)
print(A)
C = R[A]
print(C)

[[0.852 0.41  0.77  0.498]
 [0.699 0.463 0.45  0.789]
 [0.912 0.912 0.853 0.724]
 [0.087 0.027 0.089 0.778]]
[[0.087 0.027 0.089 0.498]
 [0.699 0.41  0.45  0.724]
 [0.852 0.463 0.77  0.778]
 [0.912 0.912 0.853 0.789]]
[[3 3 3 0]
 [1 0 1 2]
 [0 1 0 3]
 [2 2 2 1]]
[[[0.087 0.027 0.089 0.778]
  [0.087 0.027 0.089 0.778]
  [0.087 0.027 0.089 0.778]
  [0.852 0.41  0.77  0.498]]

 [[0.699 0.463 0.45  0.789]
  [0.852 0.41  0.77  0.498]
  [0.699 0.463 0.45  0.789]
  [0.912 0.912 0.853 0.724]]

 [[0.852 0.41  0.77  0.498]
  [0.699 0.463 0.45  0.789]
  [0.852 0.41  0.77  0.498]
  [0.087 0.027 0.089 0.778]]

 [[0.912 0.912 0.853 0.724]
  [0.912 0.912 0.853 0.724]
  [0.912 0.912 0.853 0.724]
  [0.699 0.463 0.45  0.789]]]


In [62]:
A = np.arange(1,7).reshape([2,3])
B = np.arange(7,13).reshape([3,2])
print(A)
print(B)
print(np.dot(A,B))
print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
[[1 4]
 [2 5]
 [3 6]]
